---
- name: Generate Terraform variables file
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - vault.yml

  tasks:
    - name: Generate Terraform auto tfvars file
      ansible.builtin.template:
        src: templates/terraform.auto.tfvars.j2
        dest: "{{ playbook_dir }}/../terraform/secret.auto.tfvars"
        mode: "0600"
      tags:
        - prepare
        - tfvars
